# Unrecoverable Errors with panic!

Sometimes, bad things happen in your code, and there’s nothing you can do about it. In these cases, Rust has the `panic!` macro. There are two ways to cause a panic: by taking an action that causes your code to panic (such as accessing an array out of bounds) or by explicitly calling the `panic!` macro. Both cases result in a panic in your program. By default, panics will print a failure message, unwind and clean up the stack, and then quit. You can also configure Rust to display the call stack when a panic occurs, making it easier to trace the source of the panic.

## Unwinding the Stack or Aborting in Response to a Panic

By default, when a panic occurs, the program starts unwinding, which means Rust walks back up the stack and cleans up data from each function it encounters. However, this is a lot of work. Alternatively, you can configure Rust to immediately abort, ending the program without cleaning up. This can make the resulting binary smaller. To switch from unwinding to aborting, add `panic = 'abort'` to the appropriate `[profile]` sections in your Cargo.toml file. For example, to abort on panic in release mode, add:

```toml
[profile.release]
panic = 'abort'
```

### Example: Calling panic!

Filename: src/main.rs

```rust
fn main() {
    panic!("crash and burn");
}
```

Running this program will display:

```sh
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/panic`
thread 'main' panicked at src/main.rs:2:5: crash and burn
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The `panic!` call generates an error message showing where the panic occurred.

### Using a panic! Backtrace

When a `panic!` call comes from a library because of a bug in your code, it’s useful to see a backtrace. This shows the functions called up to the point of the panic.

Filename: src/main.rs

This code panics!

```rust
fn main() {
    let v = vec![1, 2, 3];
    v[99];
}
```

Attempting to access the 100th element of a vector with only 3 elements will cause a panic. In C, this would be undefined behavior, but Rust stops execution to protect your program from vulnerabilities like buffer overreads.

Running this will display:

```sh
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/panic`
thread 'main' panicked at src/main.rs:4:6: index out of bounds: the len is 3 but the index is 99
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Setting `RUST_BACKTRACE=1` provides a backtrace:

```sh
$ RUST_BACKTRACE=1 cargo run
thread 'main' panicked at src/main.rs:4:6: index out of bounds: the len is 3 but the index is 99
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:208:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/index.rs:255:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/mod.rs:2770:9
   6: panic::main
             at ./src/main.rs:4:6
   7: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

In this backtrace, line 6 points to the code causing the problem. If you don’t want your program to panic, avoid requesting elements beyond the vector’s range. Future panics will require identifying the erroneous action and values causing the panic, and then determining the correct code behavior.

Next, we'll explore how to recover from errors using `Result`.